export const PostActionTypes = {
  SAVE_POST: 'SAVE_POST',
  EDIT_POST: 'EDIT_POST',
  SAVE_POST_SUCCESS: 'SAVE_POST_SUCCESS',
  SAVE_POST_FAILURE: 'SAVE_POST_FAILURE',

  FETCH_ALL_POSTS: 'FETCH_ALL_POSTS',
  FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
  FETCH_ALL_POSTS_FAILURE: 'FETCH_ALL_POSTS_FAILURE',
};
